getflywheel/local-addon-backups

package.json
src/main/services/cloneFromBackupService.ts
src/renderer/components/siteinfotools/SnapshotsTableList.tsx

When cloning the site, we were copying the "localBackupRepoID" into the new clone's sites.json information. This kept the new clone tied to all the backups for the old site.
Super easy fix, just took a bit to track down!
Also uncommented the "clone site" button in the dropdown menu.

feat: fix site cloning carrying over localBackupRepoID from base site

---

src/renderer/store/directorSlice.ts
src/renderer/store/snapshotsSlice.ts

Both in-progress and failed snapshots should only have a row representing it in the table for the provider that is attempting to backup and/or has failed. When switching providers, it should not be included in list of backup snapshots.
* track and check which provider requested a backup
* only show in-progress and failed backups in table if the active provider is the one that requested it
* the in-progress and failed rows are one-in-the-same so fixing one fixes the other
https://user-images.githubusercontent.com/41925404/124632332-dc018c80-de49-11eb-86fd-670310e0a60a.mov
https://user-images.githubusercontent.com/41925404/124178700-624b5680-da77-11eb-8a11-dd291254a812.mov

fix(LOC-2878): show in-progress and failed snapshot row only for the provider originating the call

---

src/main.ts

This fixes a bug where cloning a site in Local resulted in any Cloud Backups associated with the origin site carrying over to the cloned site.
Hooks into the "updateCloneSiteMetadata" filter hook in flywheel-local, and removes the localBackupRepoID associated with the clone site.
Sister PR is here: https://github.com/getflywheel/flywheel-local/pull/1134
- https://wpengine.atlassian.net/browse/LOC-2875

feat: remove localBackupRepoID from cloned sites

---

src/constants.ts
src/main.ts
src/main/hubQueries.ts
src/renderer/components/modals/BackupContents.scss
src/renderer/components/modals/BackupContents.tsx
src/renderer/components/modals/BackupEditDescriptionContents.scss
src/renderer/components/modals/BackupEditDescriptionContents.tsx
src/renderer/components/siteinfotools/SnapshotsTableList.tsx
src/renderer/store/snapshotsSlice.ts
src/renderer/store/thunks.ts

Add ability to edit a backup description!
- Adds `editSnapshotMetaData` thunk which kicks off the `graphql` mutation flow & updates the snapshot description on hub
- Adds the `editSnapshotMetaData.fulfilled` & `editSnapshotMetaData.pending` extra reducers to the `snapshotsSlice` to update UI with updated description
- Shows an error banner if there's an issue updating the description
https://user-images.githubusercontent.com/10208759/127187999-148e72ce-9001-499e-b165-7e8a97099117.mov

Edit backup description

---

src/helpers/ignoreFilesPattern.ts
src/main/cli.ts
src/renderer/components/modals/BackupContents.tsx

Adding the `.txt` extension sets Notepad as the default app when users try to edit the file.

fix: add .txt extension to ignore file

---

package.json
src/constants.ts
src/helpers/checkForDuplicateSiteName.ts
src/main.ts
src/main/cli.ts
src/main/hubQueries.ts
src/main/services/restoreService.ts
src/main/utils.ts
src/renderer.tsx
src/renderer/components/multimachinebackups/ChooseCreateSite.scss
src/renderer/components/multimachinebackups/ChooseCreateSite.tsx
src/renderer/components/multimachinebackups/CloseButtonWithStore.scss
src/renderer/components/multimachinebackups/CloseButtonWithStore.tsx
src/renderer/components/multimachinebackups/ErrorBannerContainer.scss
src/renderer/components/multimachinebackups/ErrorBannerContainer.tsx
src/renderer/components/multimachinebackups/SelectSiteBackup.scss
src/renderer/components/multimachinebackups/SelectSiteBackup.tsx
src/renderer/components/multimachinebackups/SelectSnapshot.scss
src/renderer/components/multimachinebackups/SelectSnapshot.tsx
src/renderer/components/siteinfotools/ProviderDropdown.tsx
src/renderer/components/siteinfotools/SnapshotsTableList.tsx
src/renderer/components/siteinfotools/ToolsHeader.tsx
src/renderer/store/multiMachineRestoreSlice.ts
src/renderer/store/multiMachineThunks.ts
src/renderer/store/selectors.ts
src/renderer/store/store.ts
src/types.ts
yarn.lock

This PR adds a new feature to the Cloud Backups addon that allows users to restore a backup via the "Add Site" user flow. This lets a user choose a site to restore from the complete list of sites available to them on their Cloud Provider(s), rather than needing to have the site active on their current Local install to run a clone or restore.
Important note: there are two extra improvements to this body of work that will be tackled in follow up tickets - updating the Local Database with the correct URL after the site is restored, and adding a site name as part of the site creation process.
The current "addSite" workflow in Local involves the user walking through a multi-step process, selecting data about the new Local site they're creating. Behind the scenes, this means that a …

feat: add multi-machine restore from backup workflow

---

src/main/cli.ts

When backing up large sites, especially on Windows, it's possible to get the following error: 
```
ERR_CHILD_PROCESS_STDIO_MAXBUFER
```
Quick research shows this is caused by using up the default buffer size when making exec calls. So lets bump this number up while we look into a more sustainable solution, like streams!

fix: Increase maxBuffer for exec calls.

---

package.json
src/renderer/components/siteinfotools/ProviderDropdown.scss
src/renderer/components/siteinfotools/ProviderDropdown.tsx
src/renderer/components/siteinfotools/SiteInfoToolsSection.tsx
src/renderer/components/siteinfotools/SnapshotsTableList.scss
src/renderer/components/siteinfotools/SnapshotsTableList.tsx
src/renderer/components/siteinfotools/StartBackupButton.tsx
src/renderer/components/siteinfotools/ToolsContent.tsx
src/renderer/components/siteinfotools/ToolsHeader.tsx

**NOTE - This work will depend on api changes made in the next release of local (>6.1.2). Be sure to update `package.json` before publishing the update.**
Several "offline" behavior additions to cloud backups, including tooltips and disabling of buttons. The new offline banner component was also added. Leverages the newly exposed `$offline` store from the local-addon api. Now when a user is in cloud backups and loses internet: 
- The offline banner will be displayed
- The refresh button will be removed
- The provider dropdown text will turn grey 
- The provider dropdown menu will display the tooltip
- The back up or connect provider button will be disabled with a tooltip, and
- The individual backup dropdown menu (ellipses) will show the tooltip
Note that it was easiest to just modify the …

feat(LOC-2801): offline behavior for cloud backups

---

src/renderer/components/siteinfotools/SiteInfoToolsSection.tsx
src/renderer/components/siteinfotools/SnapshotsTableList.tsx
src/renderer/helpers/thunkUtils.ts

This PR removes the red banner and error message shown when navigating to the cloud backups page when the user is offline (as determined by `navigator.onLine`). A hook was added that will also automatically refresh the cloud backups page when the user goes back online, as navigating to a site with backups while offline will show zero backups. 
Technical: Not sure if we ever get that `isHubGraphQLNetworkError` error when the user is online, but just in case, keeping it in there - maybe for if Hub is down? In that case, the red banner and error text would still be used.
An example site: 
Old behavior when navigating to the tools tab while offline: 
Note to remove this error after getting back online, the user has to manually refresh or leave and come back.
<br><br>
New behavior with new …

feat(LOC-2802): remove red offline banner from backups

---

package.json
src/renderer.tsx

This PR fixes the addition of the GoBack button from the Cloud Backups addon on every site creation screen. It should only appear on the main new site creation page, as the route it pushes brings you to that flow. 
The addon currently uses a hook called in a `NewSiteSite` component that is used in three places:
- Main Add Site flow
- Import site flow
- Pull site flow
This fix grabs the `#root` div element's first wrapper `div` child and ascertains the location based on the `data-location` attribute on that div. This solution seemed the most agnostic of Local's inner workings and the most accessible to add-on developers.

fix(LOC-3125): only add GoBack button on main add site page

---

package.json
yarn.lock

- Updates dependencies to the latest Local/Local Components.
- Bumps version to 1.5.1 ready for release.
1. Remove the “Cloud Backups” add-on if you already have it installed.
2. Run `npm pack` on this repo, install the tgz add-on file it generates (82MB is too big to upload here :-( ), and activate the add-on.
3. Back up a site.
Confirm no visual quirks or issues.

chore: (LOC-4486) Update Local and Local Components dependencies

---

package.json
src/main/hubQueries.ts

🚨 ‼️ **Ready to review, but wait until Local Hub has updated before merging this PR and re-releasing the add-on.** ‼️ 🚨 
We are working to update Local Hub to Laravel 9.
The update involves upgrading the “Lighthouse” GraphQL package for PHP, which includes a [breaking change to the GraphQL schema](https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md#orderby-argument-renamed-to-column), affecting the Backups add-on.
This PR adjusts the GraphQL request to list backups so that it still works after Local Hub is upgraded.
When we upgrade Local Hub, users will see an error message instead of their list of backups until they upgrade this plugin to the upcoming version 2.0.2.
1. Create a file at `/Users/[your-username]/Library/Application Support/Local/hub-api-settings.json` with this …

[NOJIRA] chore: fix backup list to work with upcoming Local Hub update

---

package.json
src/main/services/cloneFromBackupService.ts
yarn.lock

This change moves the site into the default group after cloning from a cloud backup. I just added the SitesOrganizationService from the service container and called the appropriate function within the backups repo. This implementation mimics what we see in AddSiteService, Importer and CloneSiteService from core Local.
I also updated the version of Local that the backups repo pulls in so that I wouldn't see any red squiggles when trying to link and run this locally for testing.
In order to test you can clone the backups repo directly into your `/Users/first.last/Library/Application Support/Local/addons` directory. Switch to this branch and run yarn install followed by yarn build in local-addon-backups. Finally, enable the addon within Local and clone a site from a backup. You guys should …

feat: move site to default group after creation

---

package.json
webpack.config.js
yarn.lock

We tried to replace `react-svg-loader` with `svg-url-loader`, but the two are not interchangeable at all and do different things. This broke the add-on when it came time to load an SVG.
I just used what we use in core, `@svgr/webpack`, with the same config as core too. This works well and no longer breaks the add-on!
Also bumped the Local core dependency.

fix: replace svg-url-loader with @svgr/webpack

---

src/renderer/components/multimachinebackups/SelectSiteBackup.scss
src/renderer/components/multimachinebackups/SelectSiteBackup.tsx

We require a unique name and allowed the users to name the new site when creating from a backup. However, we weren't updating the site domain or the path, causing things to fail. This commit updates those values when the name changes.
BasicInput has built-in invalid/error states and messages.
Also adds a fixed height to stop things from shifting when a site name is invalid.
Finally, tweaks the continue buttons padding so it doesn't shift when enabled.
To test this PR, you can pull down the code and either:
- Run `yarn install`, `yarn build`, and `npm pack`, then you should get a `tar.gz` in the root of the repo. In Local, you can navigate to the Add-ons marketplace (puzzle piece), click the "Installed" tab, and choose `Install from disk`. Select the tarball you created and wait a bit for …

fix(LOC-2973): update site domain and path when name is set

---

package.json
src/helpers/ignoreFilesPattern.ts
src/main.ts
src/main/services/cloneFromBackupService.ts
src/main/services/restoreService.ts

Windows was locking the nginx `error.log` file because it's being used by a running site's nginx process. We were going in and deleting the `app` and `logs` directories (essentially anything other than `conf`) prior to moving the backup from the tmp dir, which was causing the backup restore to break on Windows. This PR adds the `logs` directory to the list of excluded folders for files included in a backup, so we don't try to delete it anymore. It also takes the same patterns and only copies those files from the tmp directory to cover old backups. 
I also removed some site restarts that weren't actually necessary and were just increasing the time a cloud backup restore/clone was taking.
To test this PR, you can pull down the code and either:
- Pack up and install from disk. Run `yarn …

fix(LOC-3249): fix Windows backup restore caused by nginx error.log file lock

---

package.json
src/renderer/localClient/localGraphQLClient.ts
yarn.lock

We upgraded to Apollo Server 4 in Core, which switches up the subscriptions library setup. This commit just changes the `localClient` setup to match core. This fixes at least the "Back up site" button not re-enabling once the site is started. Maybe it'll fix other subtle bugs?

fix: upgrade the graphql subscriptions library per the upgrades to Local Core

---

src/main/services/restoreService.ts
src/renderer/store/thunks.ts

• **Exposes the reason for a restore failure** when available instead of using a generic error. This should help users and support, even if the messages may be more technical when presenting uncaught JS errors.
• **Prompts users to start a site** if they attempt to restore before starting. We could still improve this by (a) starting a site automatically during restore or (b) ghosting "restore" options if a site isn't started (like we do [if another backup is running](https://github.com/getflywheel/local-addon-backups/blob/5b299bdc6e98f8fd6247eea3a30c205024a130f2/src/renderer/components/siteinfotools/SnapshotsTableList.tsx#L135)), but communicating the failure reason is still an improvement that might reduce [confusion we have seen around the generic …

feature: expose restore failure reasons

---

package.json
src/constants.ts
src/helpers/ignoreFilesPattern.ts
src/main.ts
src/main/cli.ts
src/renderer/components/modals/BackupContents.tsx
yarn.lock

<strike>Tyson's input on this PR would help.</strike> [Nick says: input [gathered in Slack](https://wpengine.slack.com/archives/C06J67S6NF6/p1708522847016129), we've reinstated the "edit files to ignore" button for now.]
* Fixes [Backups add-on fails to load](https://github.com/getflywheel/flywheel-local/pull/1937#issuecomment-1946649159) that Nick found (`Error Loading Add-on: user/Application Support/Local/addons/@getflywheel-local-addon-backups/lib/renderer.js TypeError: features.isDesktopCapturerEnabled is not a function`)
* [Nick added]: Opens the backups ignore file using IPC instead of `electron-remote.shell` or `electron.shell`.
* Remove `@electron/remote` 
* [@electron/remove](https://www.npmjs.com/package/@electron/remote) recommends that you don't use it:
>⚠️ Warning! This …

Remove `@electron/remote`, use IPC instead of electron.shell for "edit files to ignore" button

---

package.json
yarn.lock

* Bumps `@getflywheel/local` and `@getflywheel/local-components` to the latest
* Bumps this add-on's version
Fixes [LOC-5971](https://wpengine.atlassian.net/browse/LOC-5971)
Testing looks good
1. `<FlyModal>` works:
2. Backing up works:
3. Restoring works:
[LOC-5971]: https://wpengine.atlassian.net/browse/LOC-5971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump Local packages
